// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CandidateHub.Database;

public partial class Candidate
{
    public int Id { get; set; }

    public string ExposeId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Email { get; set; }

    public string Comment { get; set; }

    public string PhoneNumber { get; set; }

    public string TimeInterval { get; set; }

    public string Linkedin { get; set; }

    public string GitHub { get; set; }

    public bool IsDeleted { get; set; }
}